package main

var wordlist = []string{
	"acorn", "amber", "anchor", "apple", "arrow", "atlas", "auburn", "autumn",
	"azure", "badger", "ballet", "bamboo", "basil", "basket", "bazaar", "beacon",
	"beetle", "berry", "birch", "blizzard", "blossom", "bluebird", "bonfire", "breeze",
	"briar", "bridge", "broccoli", "bronze", "brook", "butter", "cactus", "camel",
	"camera", "candle", "canyon", "caravan", "carbon", "cardinal", "cascade", "cedar",
	"celery", "champion", "channel", "charcoal", "cherry", "chisel", "cinnamon", "citrus",
	"clover", "cobalt", "coconut", "comet", "condor", "copper", "corridor", "cosmos",
	"cottage", "cricket", "crimson", "crystal", "current", "cypress", "dahlia", "daisy",
	"dandelion", "daybreak", "dewdrop", "diamond", "dolphin", "donkey", "dragonfly", "dream",
	"driftwood", "eagle", "echo", "ember", "emerald", "evergreen", "falcon", "feather",
	"fern", "fiddle", "firefly", "flame", "flamingo", "flannel", "flint", "flower",
	"forest", "fossil", "foxglove", "freedom", "frost", "galaxy", "garden", "garland",
	"garnet", "gentle", "ginger", "glacier", "glade", "glow", "granite", "grape",
	"gravel", "harmony", "harbor", "harvest", "hazel", "heather", "heron", "honey",
	"horizon", "hummingbird", "hurricane", "iceberg", "indigo", "iris", "island", "ivory",
	"jaguar", "jasmine", "jungle", "kale", "kangaroo", "kelp", "kettle", "kindness",
	"kingfisher", "lantern", "lapis", "lavender", "leaf", "lemon", "lightning", "lilac",
	"lily", "linden", "linen", "lotus", "lunar", "lupine", "luxury", "macaw",
	"magenta", "magic", "magnolia", "mango", "marble", "marigold", "meadow", "mercury",
	"meadowlark", "meteor", "mint", "mirror", "moonbeam", "morning", "moss", "mountain",
	"murmur", "mustard", "myrtle", "nectar", "nepal", "nightfall", "nimbus", "northern",
	"oak", "oasis", "ocean", "olive", "onyx", "orchid", "oriole", "otter",
	"owl", "oyster", "paddle", "palette", "palm", "panther", "parchment", "parrot",
	"pasture", "pebble", "pepper", "periwinkle", "petal", "phoenix", "pillar", "pine",
	"pistachio", "plum", "pollen", "poppy", "porcelain", "prairie", "prism", "pumpkin",
	"quartz", "quill", "rabbit", "raccoon", "radiant", "rainbow", "raven", "reed",
	"reef", "rhythm", "ribbon", "river", "robin", "rocket", "rosewood", "ruby",
	"rune", "rustic", "saffron", "sage", "sailboat", "salmon", "sapphire", "saturn",
	"scallop", "scenic", "seaweed", "serenity", "shadow", "shell", "silhouette", "silver",
	"skylark", "slate", "snowflake", "solar", "songbird", "sparrow", "spectrum", "spruce",
	"starlight", "storm", "sunflower", "sunrise", "swan", "syrup", "tangerine", "thistle",
	"thunder", "tiger", "timber", "topaz", "torch", "trout", "tulip", "tundra",
	"turquoise", "turtle", "umbrella", "uniform", "valley", "velvet", "violet", "volcano",
	"walnut", "waterfall", "whisper", "willow", "winter", "wisdom", "wisteria", "wolf",
	"wombat", "wonder", "woodland", "yarrow", "yellow", "yonder", "zephyr", "zircon",
	"zone", "zoology",
}
