// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChangeMasterPassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function CreateItem(arg1:main.Item):Promise<main.Item>;

export function CreateVault(arg1:string,arg2:string):Promise<void>;

export function DeleteItem(arg1:string):Promise<void>;

export function ExportCSV():Promise<string>;

export function ExportEncryptedJSON(arg1:string):Promise<string>;

export function ExportJSON():Promise<string>;

export function GeneratePassphrase(arg1:number):Promise<string>;

export function GeneratePassword(arg1:main.PasswordOptions):Promise<string>;

export function GetItemVersions(arg1:string):Promise<Array<main.VersionEntry>>;

export function GetItems():Promise<Array<main.Item>>;

export function GetSettings():Promise<Record<string, string>>;

export function ImportAutoCSV(arg1:string):Promise<main.ImportResult>;

export function ImportBitwardenJSON(arg1:string):Promise<main.ImportResult>;

export function ImportCSV(arg1:string,arg2:Array<main.FieldMapping>):Promise<main.ImportResult>;

export function ImportCommit(arg1:Array<main.Item>):Promise<main.ImportResult>;

export function ImportEncryptedTransfer(arg1:string,arg2:string):Promise<main.ImportResult>;

export function IsUnlocked():Promise<boolean>;

export function Lock():Promise<void>;

export function OpenVault(arg1:string):Promise<void>;

export function PrefetchFavicons():Promise<void>;

export function RestoreVersion(arg1:string):Promise<main.Item>;

export function SetAutolockMinutes(arg1:number):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function UpdateItem(arg1:main.Item):Promise<void>;

export function VaultExists():Promise<boolean>;

export function VaultPath():Promise<string>;
