// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAttachment(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddAttachment'](arg1, arg2, arg3);
}

export function AddTagBatch(arg1, arg2) {
  return window['go']['main']['App']['AddTagBatch'](arg1, arg2);
}

export function AnalyzeVault() {
  return window['go']['main']['App']['AnalyzeVault']();
}

export function BackupNow() {
  return window['go']['main']['App']['BackupNow']();
}

export function ChangeMasterPassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChangeMasterPassword'](arg1, arg2, arg3);
}

export function CloseQuickAccess() {
  return window['go']['main']['App']['CloseQuickAccess']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CreateItem(arg1) {
  return window['go']['main']['App']['CreateItem'](arg1);
}

export function CreateVault(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateVault'](arg1, arg2, arg3);
}

export function DeleteAccount() {
  return window['go']['main']['App']['DeleteAccount']();
}

export function DeleteAttachment(arg1) {
  return window['go']['main']['App']['DeleteAttachment'](arg1);
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function DeleteItems(arg1) {
  return window['go']['main']['App']['DeleteItems'](arg1);
}

export function DeleteVault(arg1) {
  return window['go']['main']['App']['DeleteVault'](arg1);
}

export function DisconnectSync() {
  return window['go']['main']['App']['DisconnectSync']();
}

export function DriveConnect(arg1, arg2) {
  return window['go']['main']['App']['DriveConnect'](arg1, arg2);
}

export function DriveDisconnect() {
  return window['go']['main']['App']['DriveDisconnect']();
}

export function DriveSetupFolder() {
  return window['go']['main']['App']['DriveSetupFolder']();
}

export function ExportCSV() {
  return window['go']['main']['App']['ExportCSV']();
}

export function ExportEncryptedJSON(arg1) {
  return window['go']['main']['App']['ExportEncryptedJSON'](arg1);
}

export function ExportJSON() {
  return window['go']['main']['App']['ExportJSON']();
}

export function ExportSelectedCSV(arg1) {
  return window['go']['main']['App']['ExportSelectedCSV'](arg1);
}

export function ExportSelectedJSON(arg1) {
  return window['go']['main']['App']['ExportSelectedJSON'](arg1);
}

export function GeneratePairingCode() {
  return window['go']['main']['App']['GeneratePairingCode']();
}

export function GeneratePassphrase(arg1) {
  return window['go']['main']['App']['GeneratePassphrase'](arg1);
}

export function GeneratePassword(arg1) {
  return window['go']['main']['App']['GeneratePassword'](arg1);
}

export function GenerateTOTPSetup(arg1) {
  return window['go']['main']['App']['GenerateTOTPSetup'](arg1);
}

export function GetAttachment(arg1) {
  return window['go']['main']['App']['GetAttachment'](arg1);
}

export function GetCurrentVaultName() {
  return window['go']['main']['App']['GetCurrentVaultName']();
}

export function GetItemVersions(arg1) {
  return window['go']['main']['App']['GetItemVersions'](arg1);
}

export function GetItems() {
  return window['go']['main']['App']['GetItems']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSyncConfig() {
  return window['go']['main']['App']['GetSyncConfig']();
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function GetTOTPCode(arg1) {
  return window['go']['main']['App']['GetTOTPCode'](arg1);
}

export function GetTOTPCodeForSecret(arg1) {
  return window['go']['main']['App']['GetTOTPCodeForSecret'](arg1);
}

export function ImportAutoCSV(arg1) {
  return window['go']['main']['App']['ImportAutoCSV'](arg1);
}

export function ImportBitwardenJSON(arg1) {
  return window['go']['main']['App']['ImportBitwardenJSON'](arg1);
}

export function ImportCSV(arg1, arg2) {
  return window['go']['main']['App']['ImportCSV'](arg1, arg2);
}

export function ImportCommit(arg1) {
  return window['go']['main']['App']['ImportCommit'](arg1);
}

export function ImportEncryptedTransfer(arg1, arg2) {
  return window['go']['main']['App']['ImportEncryptedTransfer'](arg1, arg2);
}

export function ImportKeePassDB(arg1, arg2) {
  return window['go']['main']['App']['ImportKeePassDB'](arg1, arg2);
}

export function IngestTOTPURI(arg1) {
  return window['go']['main']['App']['IngestTOTPURI'](arg1);
}

export function InstallNativeHost(arg1, arg2) {
  return window['go']['main']['App']['InstallNativeHost'](arg1, arg2);
}

export function IsUnlocked() {
  return window['go']['main']['App']['IsUnlocked']();
}

export function ListAttachments(arg1) {
  return window['go']['main']['App']['ListAttachments'](arg1);
}

export function ListTrashed() {
  return window['go']['main']['App']['ListTrashed']();
}

export function ListVaults() {
  return window['go']['main']['App']['ListVaults']();
}

export function Lock() {
  return window['go']['main']['App']['Lock']();
}

export function OpenVault(arg1, arg2) {
  return window['go']['main']['App']['OpenVault'](arg1, arg2);
}

export function PrefetchFavicons() {
  return window['go']['main']['App']['PrefetchFavicons']();
}

export function PurgeTrashed(arg1) {
  return window['go']['main']['App']['PurgeTrashed'](arg1);
}

export function RestoreTrashed(arg1) {
  return window['go']['main']['App']['RestoreTrashed'](arg1);
}

export function RestoreVersion(arg1) {
  return window['go']['main']['App']['RestoreVersion'](arg1);
}

export function SetAutolockMinutes(arg1) {
  return window['go']['main']['App']['SetAutolockMinutes'](arg1);
}

export function SetCategoryBatch(arg1, arg2) {
  return window['go']['main']['App']['SetCategoryBatch'](arg1, arg2);
}

export function SetCloseToTray(arg1) {
  return window['go']['main']['App']['SetCloseToTray'](arg1);
}

export function SetFavoriteBatch(arg1, arg2) {
  return window['go']['main']['App']['SetFavoriteBatch'](arg1, arg2);
}

export function SetQuickAccess(arg1) {
  return window['go']['main']['App']['SetQuickAccess'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function SetSyncConfig(arg1, arg2) {
  return window['go']['main']['App']['SetSyncConfig'](arg1, arg2);
}

export function SetTrashDays(arg1) {
  return window['go']['main']['App']['SetTrashDays'](arg1);
}

export function SyncNow() {
  return window['go']['main']['App']['SyncNow']();
}

export function UninstallNativeHost() {
  return window['go']['main']['App']['UninstallNativeHost']();
}

export function UpdateItem(arg1) {
  return window['go']['main']['App']['UpdateItem'](arg1);
}

export function ValidateTOTPSecret(arg1) {
  return window['go']['main']['App']['ValidateTOTPSecret'](arg1);
}

export function VaultDir() {
  return window['go']['main']['App']['VaultDir']();
}
