// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTagBatch(arg1:Array<string>,arg2:string):Promise<void>;

export function AnalyzeVault():Promise<main.HealthReport>;

export function ChangeMasterPassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function CreateItem(arg1:main.Item):Promise<main.Item>;

export function CreateVault(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteAccount():Promise<void>;

export function DeleteItem(arg1:string):Promise<void>;

export function DeleteItems(arg1:Array<string>):Promise<void>;

export function DeleteVault(arg1:string):Promise<void>;

export function ExportCSV():Promise<string>;

export function ExportEncryptedJSON(arg1:string):Promise<string>;

export function ExportJSON():Promise<string>;

export function ExportSelectedCSV(arg1:Array<string>):Promise<string>;

export function ExportSelectedJSON(arg1:Array<string>):Promise<string>;

export function GeneratePassphrase(arg1:number):Promise<string>;

export function GeneratePassword(arg1:main.PasswordOptions):Promise<string>;

export function GenerateTOTPSetup(arg1:string):Promise<main.TOTPSetupInfo>;

export function GetCurrentVaultName():Promise<string>;

export function GetItemVersions(arg1:string):Promise<Array<main.VersionEntry>>;

export function GetItems():Promise<Array<main.Item>>;

export function GetSettings():Promise<Record<string, string>>;

export function GetTOTPCode(arg1:string):Promise<main.TOTPCode>;

export function GetTOTPCodeForSecret(arg1:string):Promise<main.TOTPCode>;

export function ImportAutoCSV(arg1:string):Promise<main.ImportResult>;

export function ImportBitwardenJSON(arg1:string):Promise<main.ImportResult>;

export function ImportCSV(arg1:string,arg2:Array<main.FieldMapping>):Promise<main.ImportResult>;

export function ImportCommit(arg1:Array<main.Item>):Promise<main.ImportResult>;

export function ImportEncryptedTransfer(arg1:string,arg2:string):Promise<main.ImportResult>;

export function IngestTOTPURI(arg1:string):Promise<string>;

export function IsUnlocked():Promise<boolean>;

export function ListVaults():Promise<Array<main.VaultInfo>>;

export function Lock():Promise<void>;

export function OpenVault(arg1:string,arg2:string):Promise<void>;

export function PrefetchFavicons():Promise<void>;

export function RestoreVersion(arg1:string):Promise<main.Item>;

export function SetAutolockMinutes(arg1:number):Promise<void>;

export function SetCategoryBatch(arg1:Array<string>,arg2:string):Promise<void>;

export function SetFavoriteBatch(arg1:Array<string>,arg2:boolean):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function UpdateItem(arg1:main.Item):Promise<void>;

export function ValidateTOTPSecret(arg1:string):Promise<void>;

export function VaultDir():Promise<string>;
